#!/usr/bin/env bash
# ============================================================================
# Runs AFTER regen_all_RMSE_relative.sh, server-side, so the pipeline completes
# without needing an interactive session.
#
#   1. verify the regeneration was clean (no errors, expected figure counts)
#   2. sync figures + report into both site repos
#   3. commit + push panops-data-registry
#   4. publish fluxVSmortality (clone -> rsync -> commit -> push)
#   5. commit ESA-FORTRACK  (push needs the user's credentials)
#
# GUARD: if step 1 fails, nothing is committed or pushed. A broken regeneration
# must never reach the published site.
# ============================================================================
set -uo pipefail
cd /mnt/gsdata/projects/panops/panops-data-registry/data/flux
export GIT_SSH_COMMAND='env -u LD_LIBRARY_PATH ssh'
LOG=logs/finish_publish.log
: > "$LOG"
say(){ echo "$@" | tee -a "$LOG"; }

# ---- 1. verify -------------------------------------------------------------
say "=== verifying regeneration ==="
ERRS=$(grep -lciE "^error" logs/regen_*.log 2>/dev/null | wc -l)
say "  logs containing errors: $ERRS"
BAD=0
for D in "plots/V10" "plots/V10/tuned_exp02" "plots/V10/XGBoost" "plots/V10/LightGBM" "plots/V10/LightGBM_tuned"; do
  for DS in all_sites sites_with_high_Tcover; do
    N=$(find "$D/$DS/RMSE" -name '*.png' 2>/dev/null | wc -l)
    say "  $D/$DS/RMSE: $N png"
    [ "$N" -lt 100 ] && { say "    ^ TOO FEW (expected ~102)"; BAD=1; }
  done
done
if [ "$ERRS" -gt 0 ] || [ "$BAD" -ne 0 ]; then
  say "!! verification FAILED - not committing or pushing. Inspect logs/regen_*.log"
  echo "FINISH_EXIT=1" >> "$LOG"; exit 1
fi
say "  verification passed"

# ---- 2. sync into the two site repos ---------------------------------------
say "=== syncing to repos ==="
for RD in "fluxVSmortality/v10" "ESA-FORTRACK/D2.2_datasets_and_tools/EFPs_mortality"; do
  cp plots/V10/V10_report.html "$RD/index.html"
  rsync -a --exclude='*.pdf' plots/V10/all_sites/RMSE/              "$RD/all_sites/RMSE/"
  rsync -a --exclude='*.pdf' plots/V10/sites_with_high_Tcover/RMSE/ "$RD/sites_with_high_Tcover/RMSE/"
  for SUB in tuned_exp02 XGBoost LightGBM LightGBM_tuned; do
    for DS in all_sites sites_with_high_Tcover; do
      [ -d "plots/V10/$SUB/$DS/RMSE" ] && \
        rsync -a --exclude='*.pdf' "plots/V10/$SUB/$DS/RMSE/" "$RD/$SUB/$DS/RMSE/"
    done
  done
  say "  synced $RD"
done

# ---- 3. panops -------------------------------------------------------------
say "=== panops-data-registry ==="
cd /mnt/gsdata/projects/panops/panops-data-registry
git add -A -- data/flux ':!data/flux/FluxNet_oldV' \
  ':!data/flux/plots/V10/XGBoost/metrics_comparison.html' \
  ':!data/flux/plots/V10/XGBoost/metrics_comparison_files' >> "data/flux/$LOG" 2>&1
git commit -q -F - >> "data/flux/$LOG" 2>&1 <<'MSG'
V10: report RMSE figures as relative RMSE (%) and add mean % improvements

All RMSE-related figures, for every learner variant and both datasets:
- paired violin (Sec 3): y is now rRMSE (%) = 100 * per-site RMSE / that
  response's network-mean observed value. Normalising by a per-response constant
  puts all five EFPs on one comparable "% of typical magnitude" scale while
  avoiding the heavy tail that per-site normalisation produces at low-mean sites
  (p99 ~66-90 % vs ~150-266 %).
- delta figures (Sec 5, 6, 9): dRMSE is now a % change,
  100 * (RMSE_withD - RMSE_withoutD) / RMSE_withoutD; negative = less error.
- mean % improvement annotations added: "N% of sites improved | mean +-X%" on the
  per-site bars, and mean % printed per Low/Mid/High category and per IGBP class.

IMPORTANT: every reported percentage is UNCHANGED. A constant per-response
denominator cancels in each ratio, so the labels match the previous absolute
figures exactly and stay consistent with the metrics tables and the six-way
comparison figures. Only axis units and the added annotations differ. (Per-site
normalisation was tried first and rejected: it shifted the headline numbers -
e.g. M1->M2 GPPsat would have read -17.4 % instead of -9.7 %.)

Regenerated by scripts/regen_all_RMSE_relative.sh across baseline RF, exp02,
XGBoost, LightGBM and LightGBM-tuned.

Co-Authored-By: Claude Opus 4.8 <noreply@anthropic.com>
MSG
git push origin main >> "data/flux/$LOG" 2>&1 && say "  panops pushed" || say "  panops push FAILED"
cd /mnt/gsdata/projects/panops/panops-data-registry/data/flux

# ---- 4. live site ----------------------------------------------------------
say "=== fluxVSmortality (live site) ==="
bash scripts/push_fluxVSmortality.sh \
  "V10: RMSE figures as relative RMSE (%) + mean % improvement annotations" >> "$LOG" 2>&1 \
  && say "  live site pushed" || say "  live site push FAILED"

# ---- 5. ESA (commit only; push needs the user) ------------------------------
say "=== ESA-FORTRACK (commit only) ==="
cd ESA-FORTRACK
git add D2.2_datasets_and_tools/EFPs_mortality >> "../$LOG" 2>&1
git commit -q -m "V10 report: relative RMSE (%) figures + mean % improvement annotations" \
  -m "All RMSE figures now report relative RMSE (%) and delta RMSE (%) with mean %
improvement annotations. Reported percentages are unchanged - only axis units
and annotations differ." \
  -m "Co-Authored-By: Claude Opus 4.8 <noreply@anthropic.com>" >> "../$LOG" 2>&1 \
  && say "  ESA committed (needs your: git push origin main)" || say "  ESA: nothing to commit"

say "ALL DONE"
echo "FINISH_EXIT=0" >> "/mnt/gsdata/projects/panops/panops-data-registry/data/flux/$LOG"
